artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/uc?export=download&id=1z0mreUtRmR-P-magILsDR3T7M6IkGXtY
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_data_dir: artifacts/data_ingestion

  