artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/uc?export=download&id=1z0mreUtRmR-P-magILsDR3T7M6IkGXtY
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_data_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_base_model_path: artifacts/base_model/updated_base_model.h5


model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/trained_model.h5